import {SparklesCore} from "@/common/Sparkles";
import Form from "@/components/Contact/Form";
import Curve from '@/components/Layout/Curve'
import Head from 'next/head'
import getScheduledDays from "../../../lib/getScheduledDays";

export default function Contact({dates = [] }) {
    return (
        <>
            <Head>
                <title>Contact form</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Curve>

                <div className="mt-36 flex justify-center ">
                    <div className=" w-full bg-black flex flex-col items-center justify-center overflow-hidden rounded-md absolute -z-10 top-16">
                        <h1 className=" text-xl text-center text-white relative ">
                            Book a photo-shoot day
                        </h1>
                        <div className="w-[40rem] h-40 relative">
                            {/* Gradients */}
                            <div className="absolute inset-x-20 top-0 bg-gradient-to-r from-transparent via-indigo-500 to-transparent h-[2px] w-3/4 blur-sm" />
                            <div className="absolute inset-x-20 top-0 bg-gradient-to-r from-transparent via-indigo-500 to-transparent h-px w-3/4" />
                            <div className="absolute inset-x-60 top-0 bg-gradient-to-r from-transparent via-sky-500 to-transparent h-[5px] w-1/4 blur-sm" />
                            <div className="absolute inset-x-60 top-0 bg-gradient-to-r from-transparent via-sky-500 to-transparent h-px w-1/4" />

                            {/* Core component */}
                            <SparklesCore
                                background="transparent"
                                minSize={0.4}
                                maxSize={1}
                                particleDensity={1200}
                                className="w-full h-full"
                                particleColor="#FFFFFF"
                            />

                            {/* Radial Gradient to prevent sharp edges */}
                            <div className="absolute inset-0 w-full h-full bg-black [mask-image:radial-gradient(350px_200px_at_top,transparent_20%,white)]"></div>
                        </div>

                    </div>
                    <Form dates={dates}/>
                </div>
            </Curve>
        </>
    )
}



export async function getStaticProps() {
    const results = await getScheduledDays();

    let dates = [];

    let i = 0;
    for (let result of results.bookedDays) {
        dates.push(result.date);
        i++;
    }
    return {
        props: {
            dates: dates,
        },
    };
}
